/**
 * ChronicleView — The Three-Layer Progressive Disclosure
 *
 * Layer 1 (Story): Full narrative with literary typography. Nothing else.
 * Layer 2 (Identity): Civilization type, rarity, player factions.
 * Layer 3 (Action): Download, Share, Play Again CTAs.
 *
 * Typography: Cinzel for titles, Cormorant Garamond for body, drop cap.
 * Max reading width: 680px (Medium's optimal).
 */

import { useState, useEffect, useRef } from "react";
import { Link, useParams } from "wouter";
import { trpc } from "@/lib/trpc";
import {
  ChevronRight,
  Download,
  Share2,
  Swords,
  Eye,
  Scroll,
  Crown,
  Sword,
  Sparkles,
  Scale,
  ArrowLeft,
} from "lucide-react";
import { toast } from "sonner";

const CIV_CONFIG: Record<string, { label: string; icon: typeof Crown; color: string; description: string }> = {
  warrior_empire: {
    label: "Warrior Empire",
    icon: Sword,
    color: "text-red-400",
    description: "A civilization forged in the fires of conquest.",
  },
  enlightened_republic: {
    label: "Enlightened Republic",
    icon: Sparkles,
    color: "text-cyan-400",
    description: "A civilization that reached for the divine through knowledge.",
  },
  merchant_federation: {
    label: "Merchant Federation",
    icon: Scale,
    color: "text-amber-400",
    description: "A civilization where everything had a price — and someone always paid.",
  },
  balanced: {
    label: "Balanced Civilization",
    icon: Crown,
    color: "text-zinc-300",
    description: "A civilization of contradictions: violent peacemakers, generous thieves.",
  },
};

const RARITY_GLOW: Record<string, string> = {
  common: "",
  rare: "text-blue-400",
  epic: "text-purple-400",
  legendary: "text-amber-400",
};

const SIN_COLORS: Record<string, string> = {
  wrath: "text-red-400",
  sloth: "text-purple-400",
  greed: "text-amber-400",
  envy: "text-emerald-400",
  pride: "text-cyan-400",
  lust: "text-pink-400",
  gluttony: "text-orange-400",
};

export default function ChronicleView() {
  const { gameId } = useParams<{ gameId: string }>();
  const [layer2Visible, setLayer2Visible] = useState(false);
  const layer2Ref = useRef<HTMLDivElement>(null);

  const { data: chronicle, isLoading } = trpc.game.getChronicle.useQuery(
    { gameId: gameId! },
    { enabled: !!gameId }
  );

  // View count is incremented automatically by the getChronicle query

  // Intersection observer for Layer 2 reveal
  useEffect(() => {
    if (!layer2Ref.current) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setLayer2Visible(true);
          observer.disconnect();
        }
      },
      { threshold: 0.3 }
    );
    observer.observe(layer2Ref.current);
    return () => observer.disconnect();
  }, [chronicle]);

  const handleShare = async () => {
    const url = window.location.href;
    const title = chronicle?.title || "A Chronicle of Sins";
    if (navigator.share) {
      try {
        await navigator.share({ title, url, text: chronicle?.excerpt || "" });
      } catch {
        // User cancelled
      }
    } else {
      await navigator.clipboard.writeText(url);
      toast.success("Link copied — let others read your history.");
    }
  };

  const handleDownload = () => {
    if (!chronicle) return;
    const content = `${chronicle.title}\n\n${chronicle.full_text}\n\n---\nGenerated by 7 Deadly Sins Card Game\n${window.location.href}`;
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `chronicle-${chronicle.title.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Chronicle saved — keep your history forever.");
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-[#0A0A0F] flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <Scroll className="w-10 h-10 text-amber-500/60 animate-pulse" />
          <p className="text-amber-200/60 text-sm font-[Cinzel] tracking-wider animate-pulse">
            THE CHRONICLER IS WRITING YOUR HISTORY...
          </p>
        </div>
      </div>
    );
  }

  if (!chronicle) {
    return (
      <div className="min-h-screen bg-[#0A0A0F] flex items-center justify-center">
        <div className="text-center">
          <Scroll className="w-12 h-12 text-zinc-700 mx-auto mb-4" />
          <p className="text-zinc-400 font-['Cormorant_Garamond'] text-xl italic mb-4">
            This chronicle has been lost to time.
          </p>
          <Link
            href="/chronicles"
            className="text-amber-500/60 hover:text-amber-400 text-sm font-[Cinzel] tracking-wider transition-colors"
          >
            Browse other chronicles
          </Link>
        </div>
      </div>
    );
  }

  const civConfig = CIV_CONFIG[chronicle.civilization_type] || CIV_CONFIG.balanced;
  const CivIcon = civConfig.icon;
  const rarityColor = RARITY_GLOW[chronicle.rarity_tier] || "";
  const playerFactions = Array.isArray(chronicle.player_factions) ? chronicle.player_factions : [];

  // Split text into paragraphs for drop cap treatment
  const paragraphs = (chronicle.full_text || "").split("\n\n").filter((p: string) => p.trim());
  const firstParagraph = paragraphs[0] || "";
  const restParagraphs = paragraphs.slice(1);
  const firstLetter = firstParagraph.charAt(0);
  const restOfFirst = firstParagraph.slice(1);

  return (
    <div className="min-h-screen bg-[#0A0A0F] text-zinc-100">
      {/* ─── LAYER 1: THE STORY ─── */}
      <div className="relative">
        {/* Subtle gradient overlay */}
        <div className="absolute inset-0 bg-gradient-to-b from-amber-900/5 via-transparent to-transparent pointer-events-none" />

        <div className="relative max-w-[680px] mx-auto px-6 pt-16 pb-12">
          {/* Back link */}
          <Link
            href="/chronicles"
            className="text-amber-500/50 hover:text-amber-400 text-sm font-[Cinzel] tracking-wider mb-10 inline-flex items-center gap-1.5 transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" /> Chronicles
          </Link>

          {/* Rarity badge (if not common) */}
          {chronicle.rarity_tier !== "common" && (
            <div className={`mb-6 text-xs font-[Cinzel] tracking-[0.2em] ${rarityColor}`}>
              ✦ {chronicle.rarity_tier.toUpperCase()} CHRONICLE
            </div>
          )}

          {/* Title — Cinzel Decorative style */}
          <h1
            className="font-[Cinzel] text-2xl sm:text-3xl md:text-[32px] leading-tight text-[#C9A84C] mb-10"
            style={{ fontWeight: 700 }}
          >
            {chronicle.title}
          </h1>

          {/* Drop cap + first paragraph */}
          <div className="font-['Cormorant_Garamond'] text-lg leading-[1.7] text-zinc-300 mb-8">
            <span
              className="float-left text-[64px] leading-[0.8] font-[Cinzel] text-amber-500/80 mr-3 mt-1"
              style={{ fontWeight: 700 }}
            >
              {firstLetter}
            </span>
            <span>{restOfFirst}</span>
          </div>

          {/* Rest of the chronicle */}
          {restParagraphs.map((paragraph: string, i: number) => (
            <p
              key={i}
              className="font-['Cormorant_Garamond'] text-lg leading-[1.7] text-zinc-300 mb-6"
            >
              {paragraph}
            </p>
          ))}
        </div>
      </div>

      {/* ─── LAYER 2: THE IDENTITY ─── */}
      <div
        ref={layer2Ref}
        className={`transition-all duration-1000 ${
          layer2Visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
        }`}
      >
        <div className="max-w-[680px] mx-auto px-6 py-12 border-t border-zinc-800/50">
          {/* Civilization type */}
          <div className="flex items-center gap-3 mb-4">
            <CivIcon className={`w-6 h-6 ${civConfig.color}`} />
            <div>
              <h3 className={`font-[Cinzel] text-sm tracking-wider ${civConfig.color}`}>
                {civConfig.label}
              </h3>
              <p className="text-zinc-500 font-['Cormorant_Garamond'] text-sm italic">
                {civConfig.description}
              </p>
            </div>
          </div>

          {/* Match stats */}
          <div className="grid grid-cols-3 gap-4 my-8">
            <div className="text-center">
              <div className="text-2xl font-[Cinzel] text-amber-200/80">
                {chronicle.total_rounds}
              </div>
              <div className="text-xs text-zinc-500 font-[Cinzel] tracking-wider mt-1">
                ROUNDS
              </div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-[Cinzel] text-amber-200/80">
                {playerFactions.length}
              </div>
              <div className="text-xs text-zinc-500 font-[Cinzel] tracking-wider mt-1">
                PLAYERS
              </div>
            </div>
            <div className="text-center">
              <div className="flex items-center justify-center gap-1">
                <Eye className="w-4 h-4 text-zinc-500" />
                <span className="text-2xl font-[Cinzel] text-amber-200/80">
                  {chronicle.view_count || 0}
                </span>
              </div>
              <div className="text-xs text-zinc-500 font-[Cinzel] tracking-wider mt-1">
                READS
              </div>
            </div>
          </div>

          {/* Player factions */}
          {playerFactions.length > 0 && (
            <div className="space-y-2 mb-8">
              <h4 className="text-xs text-zinc-500 font-[Cinzel] tracking-wider mb-3">
                THE PLAYERS
              </h4>
              <div className="flex flex-wrap gap-3">
                {playerFactions.map((pf: any, i: number) => (
                  <div
                    key={i}
                    className="flex items-center gap-2 px-3 py-1.5 rounded-full border border-zinc-800/50 bg-zinc-900/50"
                  >
                    <span className={`text-sm font-[Cinzel] ${SIN_COLORS[pf.faction] || "text-zinc-400"}`}>
                      {pf.faction ? pf.faction.charAt(0).toUpperCase() + pf.faction.slice(1) : "?"}
                    </span>
                    <span className="text-sm text-zinc-400">{pf.name}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ─── LAYER 3: THE ACTION ─── */}
      <div className="max-w-[680px] mx-auto px-6 pb-20">
        <div className="border-t border-zinc-800/50 pt-10">
          <div className="flex flex-col sm:flex-row gap-3">
            {/* Download */}
            <button
              onClick={handleDownload}
              className="flex items-center justify-center gap-2 px-5 py-2.5 bg-zinc-800/60 border border-zinc-700/50 text-zinc-300 hover:text-amber-200 hover:border-amber-500/30 rounded transition-all font-[Cinzel] text-sm tracking-wider"
            >
              <Download className="w-4 h-4" />
              Keep your chronicle forever
            </button>

            {/* Share */}
            <button
              onClick={handleShare}
              className="flex items-center justify-center gap-2 px-5 py-2.5 bg-zinc-800/60 border border-zinc-700/50 text-zinc-300 hover:text-amber-200 hover:border-amber-500/30 rounded transition-all font-[Cinzel] text-sm tracking-wider"
            >
              <Share2 className="w-4 h-4" />
              Let others read your history
            </button>

            {/* Play Again */}
            <Link
              href="/"
              className="flex items-center justify-center gap-2 px-5 py-2.5 bg-amber-600/20 border border-amber-500/30 text-amber-400 hover:bg-amber-600/30 rounded transition-all font-[Cinzel] text-sm tracking-wider"
            >
              <Swords className="w-4 h-4" />
              Write another chapter
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
