/**
 * Campaign mode — 21 hand-tuned scenarios (3 acts per sin) plus framing.
 *
 * Each mission specifies:
 *  - the player's forced sin + curated 30-card deck
 *  - a boss with a forced sin, 30-card deck (containing exactly one twist
 *    card from `bossCards.ts`), HP modifier, and AI personality
 *  - hand-written intro / outro / defeat lines (the "framing"); mid-fight
 *    quips are still generated by `aiNarrator.ts` ("AI flourishes")
 *  - linear unlock chain via `unlockedBy`
 *
 * Phase 1 ships with the three Wrath acts fully written and the remaining
 * 18 missions stubbed via `comingSoon: true` so the selector renders the
 * full 7×3 grid but only the live acts can be entered. Subsequent commits
 * fill in the stubs.
 */

import { ALL_DECKS } from "./cardData";
import type { SinType } from "./gameTypes";
import { BOSS_CARDS } from "./bossCards";

export interface CampaignBoss {
  /** Display name shown above the boss portrait. */
  name: string;
  /** Boss's faction. Often matches the mission sin (mirror match) but doesn't have to. */
  sin: SinType;
  /** Title/epithet rendered as a subtitle. */
  epithet: string;
  /** 30-card deck. Must contain exactly one boss twist card ID. */
  deck: string[];
  /** Optional flavor name for the bot personality (defaults to a random one). */
  personality?: string;
}

export interface CampaignMission {
  id: string;
  sin: SinType;
  act: 1 | 2 | 3;
  /** Mission title shown on the selector tile and the intro overlay. */
  title: string;
  /** One-sentence hook on the selector tile. */
  hook: string;
  /** Pre-fight narrator monologue (3–6 sentences). */
  intro: string;
  /** Victory narrator outro (2–4 sentences). */
  outro: string;
  /** Defeat narrator line (1–2 sentences). */
  defeatLine: string;
  /** Player's forced sin — they cannot choose a different one. */
  playerDeck: string[];
  boss: CampaignBoss;
  /** Mission ID that must be completed first. `null` = always available. */
  unlockedBy: string | null;
  /** When true, the mission shows in the selector but cannot be started. */
  comingSoon?: boolean;
}

// ─── Helpers ─────────────────────────────────────────────────────

/**
 * Build a 30-card deck from a faction's pool with one twist card seeded at
 * the top. The remaining 29 slots come from the faction's first 29 PvP
 * cards, deterministically ordered so the same mission produces the same
 * deck composition (the engine still shuffles before play).
 */
function bossDeck(sin: SinType, twistCardId: string): string[] {
  const factionCards = ALL_DECKS[sin].slice(0, 29).map((c) => c.id);
  return [twistCardId, ...factionCards];
}

/** Player decks default to the first 30 cards of the faction (deterministic). */
function playerStarterDeck(sin: SinType): string[] {
  return ALL_DECKS[sin].slice(0, 30).map((c) => c.id);
}

// ─── Stub builder for the 18 unwritten missions ──────────────────

function stub(id: string, sin: SinType, act: 1 | 2 | 3, title: string, hook: string): CampaignMission {
  return {
    id,
    sin,
    act,
    title,
    hook,
    intro: "(Coming soon — this scenario hasn't been written yet.)",
    outro: "",
    defeatLine: "",
    playerDeck: playerStarterDeck(sin),
    boss: {
      name: "TBD",
      sin,
      epithet: "TBD",
      deck: playerStarterDeck(sin),
    },
    unlockedBy: act === 1 ? null : `${sin}_${act - 1}`,
    comingSoon: true,
  };
}

// ─── Wrath: The Forge / The Berserker / The Apostate ─────────────

const WRATH_ACT_1: CampaignMission = {
  id: "wrath_1",
  sin: "wrath",
  act: 1,
  title: "The Forge",
  hook: "A smith who beats sinners flat for fun.",
  intro:
    "You walk into the Forge expecting heat. You don't get heat. You get a man who's been hammering iron for so long he's forgotten the difference between metal and bone. " +
    "The Forgemaster doesn't speak. He barely looks up. He just lifts the hammer. " +
    "Wrath is the only sin that doesn't apologise. Show him you mean it.",
  outro:
    "The hammer rings once more, then quiet. The Forgemaster nods at you the way blacksmiths nod at finished work. " +
    "You're not done. You're just temperable.",
  defeatLine: "The hammer doesn't gloat. It just rises again, waiting for the next attempt.",
  playerDeck: playerStarterDeck("wrath"),
  boss: {
    name: "The Forgemaster",
    sin: "wrath",
    epithet: "Hammer of the Pit",
    deck: bossDeck("wrath", "boss_wrath_1_hammerfall"),
    personality: "The Forgemaster",
  },
  unlockedBy: null,
};

const WRATH_ACT_2: CampaignMission = {
  id: "wrath_2",
  sin: "wrath",
  act: 2,
  title: "The Berserker",
  hook: "Skullcrusher Vex doesn't just hit you — he eats you.",
  intro:
    "Vex was a soldier once. Then a war hero. Then a problem. Now he's a story other warlords tell their children to make them eat their vegetables. " +
    "He hits hard. He hits often. And every wound he opens, he drinks. " +
    "Don't trade blows. Out-pace him.",
  outro:
    "Vex laughs as he goes down — actual laughter, not the polite kind. He respects you, in the way an avalanche respects a mountain. " +
    "You feel a little more dangerous, walking out.",
  defeatLine: "Vex tilts his head, almost flattered. Try again. He has nothing but time.",
  playerDeck: playerStarterDeck("wrath"),
  boss: {
    name: "Skullcrusher Vex",
    sin: "wrath",
    epithet: "He Who Drinks the Wound",
    deck: bossDeck("wrath", "boss_wrath_2_bloodroar"),
    personality: "Skullcrusher Vex",
  },
  unlockedBy: "wrath_1",
};

const WRATH_ACT_3: CampaignMission = {
  id: "wrath_3",
  sin: "wrath",
  act: 3,
  title: "The Apostate",
  hook: "Erebus burned a cathedral down. Then he kept going.",
  intro:
    "Erebus used to be a cleric. Then he had a theological disagreement with everyone. " +
    "He preaches now, between strikes. About how Wrath is the only honest prayer. About how the rest of you are tourists. " +
    "His Final Hour is real. He's saving it for you. Don't let him reach it cheap.",
  outro:
    "Erebus kneels — the closest thing to reverence he's offered anyone since the cathedral fell. " +
    "He won't say you've earned Wrath. He'll just stop trying to take it from you.",
  defeatLine: "Erebus smiles, almost gentle. The Apostate has time. So do you, technically.",
  playerDeck: playerStarterDeck("wrath"),
  boss: {
    name: "Erebus",
    sin: "wrath",
    epithet: "The Apostate",
    deck: bossDeck("wrath", "boss_wrath_3_finalhour"),
    personality: "Erebus",
  },
  unlockedBy: "wrath_2",
};

// ─── Full mission list ───────────────────────────────────────────

export const CAMPAIGN_MISSIONS: CampaignMission[] = [
  WRATH_ACT_1,
  WRATH_ACT_2,
  WRATH_ACT_3,

  stub("sloth_1", "sloth", 1, "The Cell", "An anchorite who hasn't moved in a decade. Reaching them is the fight."),
  stub("sloth_2", "sloth", 2, "The Drowsing", "A garden where every plant breathes you in."),
  stub("sloth_3", "sloth", 3, "The Eternal", "Something that has been here longer than the arena has."),

  stub("greed_1", "greed", 1, "The Counting House", "A clerk with a quill that draws blood as ink."),
  stub("greed_2", "greed", 2, "The Vault", "A door behind a door behind a price."),
  stub("greed_3", "greed", 3, "The Plutarch", "Owns most things, including the rules of this fight."),

  stub("envy_1", "envy", 1, "The Mirror", "Someone wearing your face. Smiling like they earned it."),
  stub("envy_2", "envy", 2, "The Twin", "Whatever you build, they build better, smaller, faster."),
  stub("envy_3", "envy", 3, "The Hollow", "An empty crown looking for a head."),

  stub("pride_1", "pride", 1, "The Throne", "A boy-king with one good speech and zero humility."),
  stub("pride_2", "pride", 2, "The Idol", "Built of statues, all of itself."),
  stub("pride_3", "pride", 3, "The Apex", "It refuses to acknowledge defeat. The fight ends when you do."),

  stub("lust_1", "lust", 1, "The Salon", "Charm with a knife in it."),
  stub("lust_2", "lust", 2, "The Snare", "Beautiful. Patient. Hungry."),
  stub("lust_3", "lust", 3, "The Devourer", "What lust looks like when it stops pretending."),

  stub("gluttony_1", "gluttony", 1, "The Feast", "An endless banquet. The plates are people."),
  stub("gluttony_2", "gluttony", 2, "The Banquet", "A host who measures guests in courses."),
  stub("gluttony_3", "gluttony", 3, "The Maw", "It just keeps eating. There is no after."),
];

const MISSIONS_BY_ID: Record<string, CampaignMission> = Object.fromEntries(
  CAMPAIGN_MISSIONS.map((m) => [m.id, m])
);

export function getMissionById(id: string): CampaignMission | undefined {
  return MISSIONS_BY_ID[id];
}

export function getMissionsForSin(sin: SinType): CampaignMission[] {
  return CAMPAIGN_MISSIONS.filter((m) => m.sin === sin).sort((a, b) => a.act - b.act);
}

/** Player has completed a mission if its id is in the completed set. */
export function isMissionUnlocked(
  mission: CampaignMission,
  completedIds: ReadonlySet<string>
): boolean {
  if (mission.comingSoon) return false;
  if (mission.unlockedBy === null) return true;
  return completedIds.has(mission.unlockedBy);
}

/** Twist card IDs referenced by missions, for test integrity checks. */
export const ALL_TWIST_CARD_IDS = new Set(BOSS_CARDS.map((c) => c.id));
