/**
 * Campaign mode — 21 hand-tuned scenarios (3 acts per sin) plus framing.
 *
 * Each mission specifies:
 *  - the player's forced sin + a 30-card deck built from a `DeckArchetype`
 *  - a boss with a forced sin, 30-card deck (always containing exactly one
 *    twist card from `bossCards.ts`), an HP boost, and a thematic archetype
 *  - hand-written intro / outro / defeat lines (the "framing"); mid-fight
 *    quips are still generated by `aiNarrator.ts` ("AI flourishes")
 *  - linear unlock chain via `unlockedBy`
 *
 * Player progression across an act: `starter` → `balanced` → `elite`.
 * Boss progression varies by sin: damage-themed sins escalate to
 * `aggressive` then `elite`; defensive sins (Sloth) lean `control`.
 */

import { ALL_DECKS } from "./cardData";
import type { CardDefinition, SinType } from "./gameTypes";
import { BOSS_CARDS } from "./bossCards";

export interface CampaignBoss {
  /** Display name shown above the boss portrait. */
  name: string;
  /** Boss's faction. Often matches the mission sin (mirror match) but doesn't have to. */
  sin: SinType;
  /** Title/epithet rendered as a subtitle. */
  epithet: string;
  /** 30-card deck. Must contain exactly one boss twist card ID. */
  deck: string[];
  /**
   * Bonus HP added on top of `STARTING_HP` after the engine initialises the
   * game. Use sparingly — acts 1 should usually be 0 (let the player learn
   * the matchup), acts 2/3 lean on this to pace the difficulty curve.
   */
  hpBoost?: number;
}

export interface CampaignMission {
  id: string;
  sin: SinType;
  act: 1 | 2 | 3;
  /** Mission title shown on the selector tile and the intro overlay. */
  title: string;
  /** One-sentence hook on the selector tile. */
  hook: string;
  /** Pre-fight narrator monologue (3–6 sentences). */
  intro: string;
  /** Victory narrator outro (2–4 sentences). */
  outro: string;
  /** Defeat narrator line (1–2 sentences). */
  defeatLine: string;
  /** Player's forced sin — they cannot choose a different one. */
  playerDeck: string[];
  boss: CampaignBoss;
  /** Mission ID that must be completed first. `null` = always available. */
  unlockedBy: string | null;
  /** When true, the mission shows in the selector but cannot be started. */
  comingSoon?: boolean;
}

// ─── Deck archetypes ─────────────────────────────────────────────
//
// Every player and boss deck is built by picking 30 cards from the
// faction's 60-card PvP pool through one of these archetype filters.
// All builders are deterministic — they don't shuffle (the engine does
// that on `startGame`). Order matters for the boss-twist seeding only,
// not for gameplay.

export type DeckArchetype =
  | "starter"      // Act 1 players: cheap cards, no epics, easy to learn
  | "balanced"     // Act 2 players / many Act 1 bosses: even mix
  | "aggressive"   // damage-leaning Act 2/3 bosses
  | "control"      // Sloth-style bosses: slowburn + defensive
  | "elite";       // Act 3 bosses + Act 3 player: full power

const DEFENSIVE_EFFECTS = new Set([
  "shield_gain",
  "shield_steal",
  "heal_block",
  "heal_gain",
  "energy_block",
] as const);

function pickStarter(pool: CardDefinition[]): CardDefinition[] {
  // Bias toward cost 0–3, no epics. Tutorial-friendly.
  const targets: { cost: number; count: number }[] = [
    { cost: 0, count: 8 },
    { cost: 1, count: 10 },
    { cost: 2, count: 8 },
    { cost: 3, count: 4 },
  ];
  const result: CardDefinition[] = [];
  const used = new Set<string>();
  for (const { cost, count } of targets) {
    pool
      .filter((c) => c.cost === cost && c.tier !== "epic" && !used.has(c.id))
      .slice(0, count)
      .forEach((c) => {
        result.push(c);
        used.add(c.id);
      });
  }
  // Pad if any cost bucket was undersized (some factions have fewer cost-3 commons).
  for (const c of pool) {
    if (result.length >= 30) break;
    if (used.has(c.id) || c.tier === "epic") continue;
    result.push(c);
    used.add(c.id);
  }
  return result.slice(0, 30);
}

function pickBalanced(pool: CardDefinition[]): CardDefinition[] {
  // Roughly the natural tier distribution: ~6 epic, ~10 rare, ~14 common.
  const epics = pool.filter((c) => c.tier === "epic").slice(0, 6);
  const rares = pool.filter((c) => c.tier === "rare").slice(0, 10);
  const commons = pool.filter((c) => c.tier === "common").slice(0, 14);
  return [...epics, ...rares, ...commons].slice(0, 30);
}

function pickAggressive(pool: CardDefinition[]): CardDefinition[] {
  // Bias toward aggressive compound pattern + epic damage cards.
  const aggressive = pool.filter((c) => c.compoundPattern === "aggressive");
  const aggrSet = new Set(aggressive.map((c) => c.id));
  const damageEpics = pool.filter(
    (c) =>
      !aggrSet.has(c.id) &&
      c.tier === "epic" &&
      c.effects.some((e) => e.type === "damage")
  );
  const damageEpicSet = new Set(damageEpics.map((c) => c.id));
  const damageRares = pool.filter(
    (c) =>
      !aggrSet.has(c.id) &&
      !damageEpicSet.has(c.id) &&
      c.tier === "rare" &&
      c.effects.some((e) => e.type === "damage")
  );
  const damageRareSet = new Set(damageRares.map((c) => c.id));
  const rest = pool.filter(
    (c) => !aggrSet.has(c.id) && !damageEpicSet.has(c.id) && !damageRareSet.has(c.id)
  );
  return [...aggressive, ...damageEpics, ...damageRares, ...rest].slice(0, 30);
}

function pickControl(pool: CardDefinition[]): CardDefinition[] {
  // Bias toward slowburn pattern + defensive effects.
  const slowburn = pool.filter((c) => c.compoundPattern === "slowburn");
  const slowSet = new Set(slowburn.map((c) => c.id));
  const defensive = pool.filter(
    (c) =>
      !slowSet.has(c.id) &&
      c.effects.some((e) => DEFENSIVE_EFFECTS.has(e.type as never))
  );
  const defSet = new Set(defensive.map((c) => c.id));
  const rest = pool.filter((c) => !slowSet.has(c.id) && !defSet.has(c.id));
  return [...slowburn, ...defensive, ...rest].slice(0, 30);
}

function pickElite(pool: CardDefinition[]): CardDefinition[] {
  // All 12 epics, then top rares by cost, then highest-cost commons.
  const epics = pool.filter((c) => c.tier === "epic");
  const rares = [...pool.filter((c) => c.tier === "rare")].sort((a, b) => b.cost - a.cost);
  const commons = [...pool.filter((c) => c.tier === "common")].sort((a, b) => b.cost - a.cost);
  return [...epics, ...rares, ...commons].slice(0, 30);
}

const ARCHETYPE_PICKERS: Record<DeckArchetype, (pool: CardDefinition[]) => CardDefinition[]> = {
  starter: pickStarter,
  balanced: pickBalanced,
  aggressive: pickAggressive,
  control: pickControl,
  elite: pickElite,
};

/** Build a 30-card player deck for a sin + archetype combination. */
export function buildArchetypeDeck(sin: SinType, archetype: DeckArchetype): string[] {
  const pool = ALL_DECKS[sin];
  return ARCHETYPE_PICKERS[archetype](pool).map((c) => c.id);
}

/**
 * Build a 30-card boss deck: pick 29 cards from the archetype, then prepend
 * the boss's twist card so it sits at index 0 before the engine shuffles.
 */
function buildBossDeck(
  sin: SinType,
  archetype: DeckArchetype,
  twistCardId: string
): string[] {
  const base = buildArchetypeDeck(sin, archetype);
  return [twistCardId, ...base.slice(0, 29)];
}

// ─── Backwards-compat call-site shims ────────────────────────────
//
// The 21 mission constants were originally authored against
// `playerStarterDeck(sin)` and `bossDeck(sin, twistCardId)`. Now that
// every player+boss pairing has an archetype, these shims accept an
// optional archetype so we don't have to rewrite every mission entry —
// just pass an archetype on Act 2 / 3 calls.

function playerStarterDeck(
  sin: SinType,
  archetype: DeckArchetype = "starter"
): string[] {
  return buildArchetypeDeck(sin, archetype);
}

function bossDeck(
  sin: SinType,
  twistCardId: string,
  archetype: DeckArchetype = "balanced"
): string[] {
  return buildBossDeck(sin, archetype, twistCardId);
}

// ─── Stub builder (kept for future stubbed missions) ─────────────

function stub(id: string, sin: SinType, act: 1 | 2 | 3, title: string, hook: string): CampaignMission {
  return {
    id,
    sin,
    act,
    title,
    hook,
    intro: "(Coming soon — this scenario hasn't been written yet.)",
    outro: "",
    defeatLine: "",
    playerDeck: playerStarterDeck(sin),
    boss: {
      name: "TBD",
      sin,
      epithet: "TBD",
      deck: playerStarterDeck(sin),
    },
    unlockedBy: act === 1 ? null : `${sin}_${act - 1}`,
    comingSoon: true,
  };
}

// ─── Wrath: The Forge / The Berserker / The Apostate ─────────────

const WRATH_ACT_1: CampaignMission = {
  id: "wrath_1",
  sin: "wrath",
  act: 1,
  title: "The Forge",
  hook: "A smith who beats sinners flat for fun.",
  intro:
    "You walk into the Forge expecting heat. You don't get heat. You get a man who's been hammering iron for so long he's forgotten the difference between metal and bone. " +
    "The Forgemaster doesn't speak. He barely looks up. He just lifts the hammer. " +
    "Wrath is the only sin that doesn't apologise. Show him you mean it.",
  outro:
    "The hammer rings once more, then quiet. The Forgemaster nods at you the way blacksmiths nod at finished work. " +
    "You're not done. You're just temperable.",
  defeatLine: "The hammer doesn't gloat. It just rises again, waiting for the next attempt.",
  playerDeck: playerStarterDeck("wrath"),
  boss: {
    name: "The Forgemaster",
    sin: "wrath",
    epithet: "Hammer of the Pit",
    deck: bossDeck("wrath", "boss_wrath_1_hammerfall"),
    // Act 1 — let the player feel the matchup at standard HP
    hpBoost: 0,
  },
  unlockedBy: null,
};

const WRATH_ACT_2: CampaignMission = {
  id: "wrath_2",
  sin: "wrath",
  act: 2,
  title: "The Berserker",
  hook: "Skullcrusher Vex doesn't just hit you — he eats you.",
  intro:
    "Vex was a soldier once. Then a war hero. Then a problem. Now he's a story other warlords tell their children to make them eat their vegetables. " +
    "He hits hard. He hits often. And every wound he opens, he drinks. " +
    "Don't trade blows. Out-pace him.",
  outro:
    "Vex laughs as he goes down — actual laughter, not the polite kind. He respects you, in the way an avalanche respects a mountain. " +
    "You feel a little more dangerous, walking out.",
  defeatLine: "Vex tilts his head, almost flattered. Try again. He has nothing but time.",
  playerDeck: playerStarterDeck("wrath", "balanced"),
  boss: {
    name: "Skullcrusher Vex",
    sin: "wrath",
    epithet: "He Who Drinks the Wound",
    deck: bossDeck("wrath", "boss_wrath_2_bloodroar", "aggressive"),
    hpBoost: 80,
  },
  unlockedBy: "wrath_1",
};

const WRATH_ACT_3: CampaignMission = {
  id: "wrath_3",
  sin: "wrath",
  act: 3,
  title: "The Apostate",
  hook: "Erebus burned a cathedral down. Then he kept going.",
  intro:
    "Erebus used to be a cleric. Then he had a theological disagreement with everyone. " +
    "He preaches now, between strikes. About how Wrath is the only honest prayer. About how the rest of you are tourists. " +
    "His Final Hour is real. He's saving it for you. Don't let him reach it cheap.",
  outro:
    "Erebus kneels — the closest thing to reverence he's offered anyone since the cathedral fell. " +
    "He won't say you've earned Wrath. He'll just stop trying to take it from you.",
  defeatLine: "Erebus smiles, almost gentle. The Apostate has time. So do you, technically.",
  playerDeck: playerStarterDeck("wrath", "elite"),
  boss: {
    name: "Erebus",
    sin: "wrath",
    epithet: "The Apostate",
    deck: bossDeck("wrath", "boss_wrath_3_finalhour", "elite"),
    hpBoost: 160,
  },
  unlockedBy: "wrath_2",
};

// ─── Sloth: The Cell / The Drowsing / The Eternal ────────────────

const SLOTH_ACT_1: CampaignMission = {
  id: "sloth_1",
  sin: "sloth",
  act: 1,
  title: "The Cell",
  hook: "An anchorite who hasn't moved in a decade. Reaching them is the fight.",
  intro:
    "They lock the doors before you arrive. Then they lock them again behind you. " +
    "The Anchorite Aldon doesn't have to fight you — he just has to wait. " +
    "He's been waiting longer than you've been alive. Hit him often, hit him fast. " +
    "If he settles in, you don't make it out.",
  outro:
    "Aldon doesn't react when you finish him. He just blinks, slowly. " +
    "You can't tell if he's seen you. The chains slacken, a little. The door stays where it is.",
  defeatLine: "Aldon doesn't smile. He resettles. He has time.",
  playerDeck: playerStarterDeck("sloth"),
  boss: {
    name: "The Anchorite Aldon",
    sin: "sloth",
    epithet: "Bound to the Cell",
    deck: bossDeck("sloth", "boss_sloth_1_ironpatience"),
    hpBoost: 0,
  },
  unlockedBy: null,
};

const SLOTH_ACT_2: CampaignMission = {
  id: "sloth_2",
  sin: "sloth",
  act: 2,
  title: "The Drowsing",
  hook: "A garden where every plant breathes you in.",
  intro:
    "Mother Slumber doesn't have a face, exactly. She has a posture. " +
    "She is sitting in the centre of a garden that drinks people quietly, and she will be very gracious about you joining the soil. " +
    "The flowers don't care who wins. They care who loses slower. " +
    "Don't slow down.",
  outro:
    "Mother Slumber bows once, the way trees bow before a storm. " +
    "The garden goes back to breathing without you in it. " +
    "You won't sleep tonight. You'll be too proud.",
  defeatLine: "You don't remember sitting down. You don't remember closing your eyes.",
  playerDeck: playerStarterDeck("sloth", "balanced"),
  boss: {
    name: "Mother Slumber",
    sin: "sloth",
    epithet: "She Who Breathes the Room Out",
    deck: bossDeck("sloth", "boss_sloth_2_drowse", "control"),
    hpBoost: 90,
  },
  unlockedBy: "sloth_1",
};

const SLOTH_ACT_3: CampaignMission = {
  id: "sloth_3",
  sin: "sloth",
  act: 3,
  title: "The Eternal",
  hook: "Something that has been here longer than the arena has.",
  intro:
    "They don't tell you what The Eternal is, because nobody knows. " +
    "The arena was built around it — the arena is, in some sense, an apology. " +
    "It does not strike. It accumulates. By round four it will own the board. By round six it will own you. " +
    "Don't let it reach round six.",
  outro:
    "The Eternal does not die so much as elsewhere. Something distant inside it stops, and somewhere else, something starts. " +
    "You leave before whatever-that-is finds you. Wrath was a tantrum. Sloth was a verdict.",
  defeatLine: "The Eternal keeps eating. It has all the time. You did not.",
  playerDeck: playerStarterDeck("sloth", "elite"),
  boss: {
    name: "Older Than the Bell",
    sin: "sloth",
    epithet: "The Eternal",
    deck: bossDeck("sloth", "boss_sloth_3_aeon", "control"),
    hpBoost: 175,
  },
  unlockedBy: "sloth_2",
};

// ─── Greed: The Counting House / The Vault / The Plutarch ───────

const GREED_ACT_1: CampaignMission = {
  id: "greed_1",
  sin: "greed",
  act: 1,
  title: "The Counting House",
  hook: "A clerk with a quill that draws blood as ink.",
  intro:
    "The Counting House isn't a building. It's an idea — that everything has a price, and someone has been keeping the receipts. " +
    "Maeven doesn't speak unless she's asking for a number. " +
    "She's been collecting on debts you don't remember owing, and keeping ledger on this fight for longer than you think. " +
    "Don't let her finish the column.",
  outro:
    "Maeven hands you back what you didn't know she'd taken. She doesn't apologize — clerks never do. " +
    "She writes a small note in your margin. You'll think about it later.",
  defeatLine: "Maeven adds you to the column without ceremony. Just a small mark.",
  playerDeck: playerStarterDeck("greed"),
  boss: {
    name: "The Clerk Maeven",
    sin: "greed",
    epithet: "Keeper of the Column",
    deck: bossDeck("greed", "boss_greed_1_tithe"),
    hpBoost: 0,
  },
  unlockedBy: null,
};

const GREED_ACT_2: CampaignMission = {
  id: "greed_2",
  sin: "greed",
  act: 2,
  title: "The Vault",
  hook: "A door behind a door behind a price.",
  intro:
    "Octavia keeps the Vault. The Vault keeps her. Nobody is sure which came first. " +
    "The trick with Octavia is that she's been billing you for every step you've taken since you walked in. " +
    "By the time you're standing in front of her, you owe more than you came in with. " +
    "Pay the debt with damage. Or don't pay it at all.",
  outro:
    "Octavia opens a door behind her, just for a moment. You see something glinting in there. " +
    "She closes it before you can ask. She nods, once. The Vault accepts you, conditionally.",
  defeatLine: "Octavia tabulates your loss without surprise. The Vault was never going to be opened by you.",
  playerDeck: playerStarterDeck("greed", "balanced"),
  boss: {
    name: "Vault-Keeper Octavia",
    sin: "greed",
    epithet: "Door Behind the Door",
    deck: bossDeck("greed", "boss_greed_2_ledger_strike", "aggressive"),
    hpBoost: 90,
  },
  unlockedBy: "greed_1",
};

const GREED_ACT_3: CampaignMission = {
  id: "greed_3",
  sin: "greed",
  act: 3,
  title: "The Plutarch",
  hook: "Owns most things, including the rules of this fight.",
  intro:
    "Cassivus does not enter. He arrives, the way weather arrives. " +
    "He owns the Counting House. He owns the Vault. He owns, technically, the room you are standing in, the air you're breathing, and several minor parts of your liver. " +
    "He doesn't fight people. He liquidates them. " +
    "Make the liquidation expensive.",
  outro:
    "Cassivus does the closest thing to surprise his face has done in fifty years. " +
    "He hands you a piece of paper. You realize it's a deed. To something. " +
    "He doesn't say what. He'll tell you the next time you meet — if there is one.",
  defeatLine: "Cassivus does not gloat. Cassivus does paperwork. Several documents related to your defeat have already been filed.",
  playerDeck: playerStarterDeck("greed", "elite"),
  boss: {
    name: "Cassivus",
    sin: "greed",
    epithet: "The Plutarch",
    deck: bossDeck("greed", "boss_greed_3_liquidation", "elite"),
    hpBoost: 175,
  },
  unlockedBy: "greed_2",
};

// ─── Envy: The Mirror / The Twin / The Hollow ────────────────────

const ENVY_ACT_1: CampaignMission = {
  id: "envy_1",
  sin: "envy",
  act: 1,
  title: "The Mirror",
  hook: "Someone wearing your face. Smiling like they earned it.",
  intro:
    "You walk in. You're already in the room. " +
    "Your reflection — but wrong, because it's looking at you and you aren't looking at it. " +
    "The Mirror has been practicing your moves. It's been practicing your face. It probably knows how you breathe by now. " +
    "Beat the version of you that doesn't have to live with you.",
  outro:
    "The Mirror cracks, decorously. The face inside it slides off. " +
    "Whatever was behind goes back to whatever it was before you arrived. " +
    "You feel slightly less like an original.",
  defeatLine: "The Mirror smiles your smile, but better. It's been watching.",
  playerDeck: playerStarterDeck("envy"),
  boss: {
    name: "The Mirror",
    sin: "envy",
    epithet: "Wearing Your Face",
    deck: bossDeck("envy", "boss_envy_1_glasswork"),
    hpBoost: 0,
  },
  unlockedBy: null,
};

const ENVY_ACT_2: CampaignMission = {
  id: "envy_2",
  sin: "envy",
  act: 2,
  title: "The Twin",
  hook: "Whatever you build, they build better, smaller, faster.",
  intro:
    "There's a story about a twin who was born late. They grew up watching the older twin — what they ate, who they kissed, what they were good at. " +
    "The older twin never noticed. The older twin is now in front of you. " +
    "You are not the older twin in this story. " +
    "Build first. Build fast. Don't show your hand.",
  outro:
    "The Twin doesn't look defeated. They look thoughtful. " +
    "They've taken notes. You'll see them again, with whatever they learned today.",
  defeatLine: "The Twin doesn't celebrate. They've already moved on to the next thing they want.",
  playerDeck: playerStarterDeck("envy", "balanced"),
  boss: {
    name: "The Twin",
    sin: "envy",
    epithet: "Born Late, Catching Up",
    deck: bossDeck("envy", "boss_envy_2_replica", "aggressive"),
    hpBoost: 90,
  },
  unlockedBy: "envy_1",
};

const ENVY_ACT_3: CampaignMission = {
  id: "envy_3",
  sin: "envy",
  act: 3,
  title: "The Hollow",
  hook: "An empty crown looking for a head.",
  intro:
    "The Hollow is what envy becomes when it eats everything in its line of sight, including itself. " +
    "There's a crown. There's nothing under it. The crown wants a head — has been wanting a head for a very long time. " +
    "The trick is not to want the crown. " +
    "The trick is to be more annoying than the crown is patient.",
  outro:
    "The Hollow inhales for the first time in a century. You feel it pull at your edges. " +
    "Then it stops. The crown clatters. " +
    "It has chosen, slowly, to want nothing for a moment. Lucky you.",
  defeatLine: "The Hollow finds something to want, briefly. You. Then loses interest, because there is so little to take.",
  playerDeck: playerStarterDeck("envy", "elite"),
  boss: {
    name: "The Hollow",
    sin: "envy",
    epithet: "An Empty Crown",
    deck: bossDeck("envy", "boss_envy_3_inheritance", "elite"),
    hpBoost: 175,
  },
  unlockedBy: "envy_2",
};

// ─── Pride: The Throne / The Idol / The Apex ─────────────────────

const PRIDE_ACT_1: CampaignMission = {
  id: "pride_1",
  sin: "pride",
  act: 1,
  title: "The Throne",
  hook: "A boy-king with one good speech and zero humility.",
  intro:
    "The Boy-King Velys is fifteen, has a kingdom to inherit, and absolutely nothing to lose. " +
    "He's been told he's special since the day he was born. He has, frankly, evidence. " +
    "He'll ask if you've heard of him. " +
    "Don't answer. Hit him before the speech lands.",
  outro:
    "Velys looks at you, genuinely surprised, and laughs. He likes you. He'll remember this. " +
    "That might be a problem later. For today, you're alive and he's impressed.",
  defeatLine: "Velys doesn't even look down at you. He's already onto the next sentence.",
  playerDeck: playerStarterDeck("pride"),
  boss: {
    name: "Boy-King Velys",
    sin: "pride",
    epithet: "One Good Speech",
    deck: bossDeck("pride", "boss_pride_1_coronation"),
    hpBoost: 0,
  },
  unlockedBy: null,
};

const PRIDE_ACT_2: CampaignMission = {
  id: "pride_2",
  sin: "pride",
  act: 2,
  title: "The Idol",
  hook: "Built of statues, all of itself.",
  intro:
    "The Idol of Selene is, technically, a religion. There are temples. There is iconography. " +
    "In front of you is a statue that has decided it's done waiting for worshippers. " +
    "It walks slow, hits enormous, and considers itself a building rather than an opponent. " +
    "Don't pray. Don't kneel. Hit the statue until it remembers it was carved by hands.",
  outro:
    "The Idol cracks at the base. It's been waiting to crack for a long time. " +
    "Whatever it represented goes back to representing nothing. " +
    "The temples will call it heresy. They aren't wrong.",
  defeatLine: "The Idol does not move to acknowledge you. It is already what it was.",
  playerDeck: playerStarterDeck("pride", "balanced"),
  boss: {
    name: "The Idol of Selene",
    sin: "pride",
    epithet: "Carved By Hands It Forgot",
    deck: bossDeck("pride", "boss_pride_2_apotheosis", "aggressive"),
    hpBoost: 90,
  },
  unlockedBy: "pride_1",
};

const PRIDE_ACT_3: CampaignMission = {
  id: "pride_3",
  sin: "pride",
  act: 3,
  title: "The Apex",
  hook: "It refuses to acknowledge defeat. The fight ends when you do.",
  intro:
    "Apex has not lost. Apex has decided this is a structural property of reality, not a fact about Apex's skill. " +
    "Apex will continue to not lose by simply not stopping. " +
    "By round six, Apex will be, in some real sense, the room. By round seven, you will be furniture. " +
    "Make this hurt before then.",
  outro:
    "Apex stops. Not falls — stops. There is no precedent for it. " +
    "Apex looks at you the way you would look at someone who broke physics. " +
    "Then Apex inclines its head, very slightly, and walks out. " +
    "Pride is not what you take. It's what you decline to keep.",
  defeatLine: "Apex did not lose. The fight simply ended in the only way it could.",
  playerDeck: playerStarterDeck("pride", "elite"),
  boss: {
    name: "Apex",
    sin: "pride",
    epithet: "Has Never",
    deck: bossDeck("pride", "boss_pride_3_unbroken", "elite"),
    hpBoost: 175,
  },
  unlockedBy: "pride_2",
};

// ─── Lust: The Salon / The Snare / The Devourer ──────────────────

const LUST_ACT_1: CampaignMission = {
  id: "lust_1",
  sin: "lust",
  act: 1,
  title: "The Salon",
  hook: "Charm with a knife in it.",
  intro:
    "Madame Vaela runs the Salon, which is a place very specifically designed for people to think they're the smartest person in the room. " +
    "You will think this. You will be wrong. " +
    "Vaela's only fight is the one where you don't notice you're fighting until you've lost. " +
    "Notice. Hit her first. Compliment her later, if you're still alive.",
  outro:
    "Vaela laughs. She enjoys this. She offers you a drink. " +
    "Don't take it, but appreciate the gesture. The Salon stays open. " +
    "You leave through a different door than you came in.",
  defeatLine: "Vaela tilts her head, charmed. You'll always be welcome at the Salon. Possibly as decoration.",
  playerDeck: playerStarterDeck("lust"),
  boss: {
    name: "Madame Vaela",
    sin: "lust",
    epithet: "Hostess of the Salon",
    deck: bossDeck("lust", "boss_lust_1_silver_tongue"),
    hpBoost: 0,
  },
  unlockedBy: null,
};

const LUST_ACT_2: CampaignMission = {
  id: "lust_2",
  sin: "lust",
  act: 2,
  title: "The Snare",
  hook: "Beautiful. Patient. Hungry.",
  intro:
    "Lyssara doesn't move toward you. She moves toward where you'll be when you've stopped paying attention. " +
    "Everything in this room was designed to make you stop paying attention — the candles, the arrangement of the furniture, the way she's sitting. " +
    "Don't relax. Don't take a breath. " +
    "The breath is when she eats.",
  outro:
    "Lyssara doesn't break eye contact even as she's defeated. She's flattered. " +
    "Few opponents she's had — and there have been a great many — have refused to relax. " +
    "She'll think about you for years.",
  defeatLine: "You don't notice the moment you lose. That's how she designed it. You'll notice afterwards, in increments, for a long time.",
  playerDeck: playerStarterDeck("lust", "balanced"),
  boss: {
    name: "Lyssara",
    sin: "lust",
    epithet: "She Who Waits",
    deck: bossDeck("lust", "boss_lust_2_snare", "aggressive"),
    hpBoost: 90,
  },
  unlockedBy: "lust_1",
};

const LUST_ACT_3: CampaignMission = {
  id: "lust_3",
  sin: "lust",
  act: 3,
  title: "The Devourer",
  hook: "What lust looks like when it stops pretending.",
  intro:
    "There is no charm here. The Devourer was charming once — the charm was a sheath. " +
    "The Devourer is what was inside the sheath. " +
    "It does not flirt. It does not offer drinks. It approaches the way a wave approaches a coastline. " +
    "Don't drown.",
  outro:
    "The Devourer holds, for a moment, exactly the shape of what it was before — beautiful, attentive, hungry. " +
    "Then it falls back into nothing recognizable. " +
    "You walk out without looking back. Looking back is how it eats.",
  defeatLine: "The Devourer takes its time. The Devourer always takes its time. There's no hurry. There never is.",
  playerDeck: playerStarterDeck("lust", "elite"),
  boss: {
    name: "The Devourer",
    sin: "lust",
    epithet: "Sheath, Discarded",
    deck: bossDeck("lust", "boss_lust_3_devour", "elite"),
    hpBoost: 175,
  },
  unlockedBy: "lust_2",
};

// ─── Gluttony: The Feast / The Banquet / The Maw ─────────────────

const GLUTTONY_ACT_1: CampaignMission = {
  id: "gluttony_1",
  sin: "gluttony",
  act: 1,
  title: "The Feast",
  hook: "An endless banquet. The plates are people.",
  intro:
    "Master Renat hosts the Feast, which is an event that has been going on, with no break, for forty years. " +
    "The plates have always been people. The guests don't notice — they're enjoying themselves. " +
    "Renat is the most enthusiastic guest. He's also the chef. He also did the marinade. " +
    "Hit him before he picks up the next fork.",
  outro:
    "Renat sets down his fork, mid-course, looking faintly disappointed. " +
    "The Feast continues, because the Feast always continues. " +
    "But your seat is empty now, and that is, in this place, the only kind of victory.",
  defeatLine: "You taste excellent, apparently.",
  playerDeck: playerStarterDeck("gluttony"),
  boss: {
    name: "Master Renat",
    sin: "gluttony",
    epithet: "Chef and Guest",
    deck: bossDeck("gluttony", "boss_gluttony_1_courses"),
    hpBoost: 0,
  },
  unlockedBy: null,
};

const GLUTTONY_ACT_2: CampaignMission = {
  id: "gluttony_2",
  sin: "gluttony",
  act: 2,
  title: "The Banquet",
  hook: "A host who measures guests in courses.",
  intro:
    "The Host is more polite than Renat. The Host is also worse. " +
    "The Host believes in pacing. The Host believes in presentation. " +
    "The Host believes everyone gets a place setting and a course number, including, importantly, you. " +
    "Don't accept the cutlery. Don't sit down.",
  outro:
    "The Host bows, the small dignified bow of a maitre d' whose night ended early. " +
    "The other guests barely notice — they're between courses. " +
    "The Host shows you out. You weren't, in the end, on the menu.",
  defeatLine: "You were a fine course. Not memorable, but fine.",
  playerDeck: playerStarterDeck("gluttony", "balanced"),
  boss: {
    name: "The Host",
    sin: "gluttony",
    epithet: "Course Number Pending",
    deck: bossDeck("gluttony", "boss_gluttony_2_invitation", "aggressive"),
    hpBoost: 90,
  },
  unlockedBy: "gluttony_1",
};

const GLUTTONY_ACT_3: CampaignMission = {
  id: "gluttony_3",
  sin: "gluttony",
  act: 3,
  title: "The Maw",
  hook: "It just keeps eating. There is no after.",
  intro:
    "The Maw is what gluttony becomes when there's nothing left to be polite about. " +
    "There's no host. There's no banquet. There's no flatware. " +
    "There's just a hole in the world that has decided to be open. " +
    "It does not consider you. Consideration is for things it hasn't eaten yet. " +
    "Hit it until it considers you. That'll be too late, but only a little.",
  outro:
    "The Maw closes. Briefly. " +
    "You're not sure if it closed because you defeated it or because it ran out of room. You don't ask. " +
    "The exit is clearly marked, for once.",
  defeatLine: "The Maw does not gloat. The Maw eats. It has always done so. It will continue.",
  playerDeck: playerStarterDeck("gluttony", "elite"),
  boss: {
    name: "The Maw",
    sin: "gluttony",
    epithet: "A Hole That Decided",
    deck: bossDeck("gluttony", "boss_gluttony_3_consumption", "elite"),
    hpBoost: 175,
  },
  unlockedBy: "gluttony_2",
};

// ─── Full mission list ───────────────────────────────────────────

export const CAMPAIGN_MISSIONS: CampaignMission[] = [
  WRATH_ACT_1,
  WRATH_ACT_2,
  WRATH_ACT_3,

  SLOTH_ACT_1,
  SLOTH_ACT_2,
  SLOTH_ACT_3,

  GREED_ACT_1,
  GREED_ACT_2,
  GREED_ACT_3,

  ENVY_ACT_1,
  ENVY_ACT_2,
  ENVY_ACT_3,

  PRIDE_ACT_1,
  PRIDE_ACT_2,
  PRIDE_ACT_3,

  LUST_ACT_1,
  LUST_ACT_2,
  LUST_ACT_3,

  GLUTTONY_ACT_1,
  GLUTTONY_ACT_2,
  GLUTTONY_ACT_3,
];

const MISSIONS_BY_ID: Record<string, CampaignMission> = Object.fromEntries(
  CAMPAIGN_MISSIONS.map((m) => [m.id, m])
);

export function getMissionById(id: string): CampaignMission | undefined {
  return MISSIONS_BY_ID[id];
}

export function getMissionsForSin(sin: SinType): CampaignMission[] {
  return CAMPAIGN_MISSIONS.filter((m) => m.sin === sin).sort((a, b) => a.act - b.act);
}

/** Player has completed a mission if its id is in the completed set. */
export function isMissionUnlocked(
  mission: CampaignMission,
  completedIds: ReadonlySet<string>
): boolean {
  if (mission.comingSoon) return false;
  if (mission.unlockedBy === null) return true;
  return completedIds.has(mission.unlockedBy);
}

/**
 * Pick the mission to surface as a "Continue" CTA. Returns null when the
 * player has no campaign history yet (the Home page just shows the regular
 * "Campaign" tile in that case).
 *
 * Priority:
 *  1. An attempted-but-not-yet-cleared mission (player hit a wall — give
 *     them a one-click jump back to it).
 *  2. The next unlocked + uncompleted mission after a cleared streak
 *     (player wants to keep going).
 *
 * `attempts` carries the number of launches per mission ID and comes from
 * `useCampaignProgress`. `completedIds` is the cleared-mission set from
 * the same hook.
 */
export function getContinueMission(
  attempts: ReadonlyMap<string, number> | Record<string, number>,
  completedIds: ReadonlySet<string>
): CampaignMission | null {
  const attemptsMap =
    attempts instanceof Map
      ? attempts
      : new Map(Object.entries(attempts));

  // Case 1 — a mission has been attempted but not cleared.
  for (const m of CAMPAIGN_MISSIONS) {
    if (m.comingSoon) continue;
    if (completedIds.has(m.id)) continue;
    if ((attemptsMap.get(m.id) ?? 0) > 0) return m;
  }

  // Case 2 — at least one mission cleared. Suggest the next available act.
  if (completedIds.size > 0) {
    for (const m of CAMPAIGN_MISSIONS) {
      if (m.comingSoon) continue;
      if (completedIds.has(m.id)) continue;
      if (isMissionUnlocked(m, completedIds)) return m;
    }
  }

  return null;
}

/** Twist card IDs referenced by missions, for test integrity checks. */
export const ALL_TWIST_CARD_IDS = new Set(BOSS_CARDS.map((c) => c.id));

// ─── Difficulty surfacing ────────────────────────────────────────
//
// Difficulty is computed (not hand-authored) so it stays in sync if we
// retune HP boosts or boss archetypes. Five tiers, mapped to a 1–5 star
// rating + a flavour label rendered on the selector tile and the intro
// panel.

export interface MissionDifficulty {
  /** 1–5 stars. */
  stars: number;
  /** Short flavour label for the chip ("Initiate", "Apex", …). */
  label: string;
  /** Hex accent colour matching the difficulty's palette. */
  accent: string;
}

const DIFFICULTY_LABELS: Record<number, string> = {
  1: "Initiate",
  2: "Apprentice",
  3: "Adept",
  4: "Reckoning",
  5: "Apex",
};

const DIFFICULTY_ACCENTS: Record<number, string> = {
  1: "#34d399", // emerald — easy
  2: "#fbbf24", // amber — easy-medium
  3: "#fb923c", // orange — medium
  4: "#f87171", // red — hard
  5: "#dc2626", // deep red — hardest
};

export function getMissionDifficulty(mission: CampaignMission): MissionDifficulty {
  // Base from act: 2 / 3 / 5 stars. Bumped to 4 for Act 2s with high HP boost
  // so the curve has room to vary without hand-authoring per mission.
  let stars = mission.act === 1 ? 2 : mission.act === 2 ? 3 : 5;
  if (mission.act === 2 && (mission.boss.hpBoost ?? 0) >= 100) stars = 4;
  stars = Math.min(5, Math.max(1, stars));
  return {
    stars,
    label: DIFFICULTY_LABELS[stars] ?? "Adept",
    accent: DIFFICULTY_ACCENTS[stars] ?? "#fb923c",
  };
}
