/**
 * Campaign mode — 21 hand-tuned scenarios (3 acts per sin) plus framing.
 *
 * Each mission specifies:
 *  - the player's forced sin + curated 30-card deck
 *  - a boss with a forced sin, 30-card deck (containing exactly one twist
 *    card from `bossCards.ts`), HP modifier, and AI personality
 *  - hand-written intro / outro / defeat lines (the "framing"); mid-fight
 *    quips are still generated by `aiNarrator.ts` ("AI flourishes")
 *  - linear unlock chain via `unlockedBy`
 *
 * Phase 1 ships with the three Wrath acts fully written and the remaining
 * 18 missions stubbed via `comingSoon: true` so the selector renders the
 * full 7×3 grid but only the live acts can be entered. Subsequent commits
 * fill in the stubs.
 */

import { ALL_DECKS } from "./cardData";
import type { SinType } from "./gameTypes";
import { BOSS_CARDS } from "./bossCards";

export interface CampaignBoss {
  /** Display name shown above the boss portrait. */
  name: string;
  /** Boss's faction. Often matches the mission sin (mirror match) but doesn't have to. */
  sin: SinType;
  /** Title/epithet rendered as a subtitle. */
  epithet: string;
  /** 30-card deck. Must contain exactly one boss twist card ID. */
  deck: string[];
  /**
   * Bonus HP added on top of `STARTING_HP` after the engine initialises the
   * game. Use sparingly — acts 1 should usually be 0 (let the player learn
   * the matchup), acts 2/3 lean on this to pace the difficulty curve.
   */
  hpBoost?: number;
}

export interface CampaignMission {
  id: string;
  sin: SinType;
  act: 1 | 2 | 3;
  /** Mission title shown on the selector tile and the intro overlay. */
  title: string;
  /** One-sentence hook on the selector tile. */
  hook: string;
  /** Pre-fight narrator monologue (3–6 sentences). */
  intro: string;
  /** Victory narrator outro (2–4 sentences). */
  outro: string;
  /** Defeat narrator line (1–2 sentences). */
  defeatLine: string;
  /** Player's forced sin — they cannot choose a different one. */
  playerDeck: string[];
  boss: CampaignBoss;
  /** Mission ID that must be completed first. `null` = always available. */
  unlockedBy: string | null;
  /** When true, the mission shows in the selector but cannot be started. */
  comingSoon?: boolean;
}

// ─── Helpers ─────────────────────────────────────────────────────

/**
 * Build a 30-card deck from a faction's pool with one twist card seeded at
 * the top. The remaining 29 slots come from the faction's first 29 PvP
 * cards, deterministically ordered so the same mission produces the same
 * deck composition (the engine still shuffles before play).
 */
function bossDeck(sin: SinType, twistCardId: string): string[] {
  const factionCards = ALL_DECKS[sin].slice(0, 29).map((c) => c.id);
  return [twistCardId, ...factionCards];
}

/** Player decks default to the first 30 cards of the faction (deterministic). */
function playerStarterDeck(sin: SinType): string[] {
  return ALL_DECKS[sin].slice(0, 30).map((c) => c.id);
}

// ─── Stub builder for the 18 unwritten missions ──────────────────

function stub(id: string, sin: SinType, act: 1 | 2 | 3, title: string, hook: string): CampaignMission {
  return {
    id,
    sin,
    act,
    title,
    hook,
    intro: "(Coming soon — this scenario hasn't been written yet.)",
    outro: "",
    defeatLine: "",
    playerDeck: playerStarterDeck(sin),
    boss: {
      name: "TBD",
      sin,
      epithet: "TBD",
      deck: playerStarterDeck(sin),
    },
    unlockedBy: act === 1 ? null : `${sin}_${act - 1}`,
    comingSoon: true,
  };
}

// ─── Wrath: The Forge / The Berserker / The Apostate ─────────────

const WRATH_ACT_1: CampaignMission = {
  id: "wrath_1",
  sin: "wrath",
  act: 1,
  title: "The Forge",
  hook: "A smith who beats sinners flat for fun.",
  intro:
    "You walk into the Forge expecting heat. You don't get heat. You get a man who's been hammering iron for so long he's forgotten the difference between metal and bone. " +
    "The Forgemaster doesn't speak. He barely looks up. He just lifts the hammer. " +
    "Wrath is the only sin that doesn't apologise. Show him you mean it.",
  outro:
    "The hammer rings once more, then quiet. The Forgemaster nods at you the way blacksmiths nod at finished work. " +
    "You're not done. You're just temperable.",
  defeatLine: "The hammer doesn't gloat. It just rises again, waiting for the next attempt.",
  playerDeck: playerStarterDeck("wrath"),
  boss: {
    name: "The Forgemaster",
    sin: "wrath",
    epithet: "Hammer of the Pit",
    deck: bossDeck("wrath", "boss_wrath_1_hammerfall"),
    // Act 1 — let the player feel the matchup at standard HP
    hpBoost: 0,
  },
  unlockedBy: null,
};

const WRATH_ACT_2: CampaignMission = {
  id: "wrath_2",
  sin: "wrath",
  act: 2,
  title: "The Berserker",
  hook: "Skullcrusher Vex doesn't just hit you — he eats you.",
  intro:
    "Vex was a soldier once. Then a war hero. Then a problem. Now he's a story other warlords tell their children to make them eat their vegetables. " +
    "He hits hard. He hits often. And every wound he opens, he drinks. " +
    "Don't trade blows. Out-pace him.",
  outro:
    "Vex laughs as he goes down — actual laughter, not the polite kind. He respects you, in the way an avalanche respects a mountain. " +
    "You feel a little more dangerous, walking out.",
  defeatLine: "Vex tilts his head, almost flattered. Try again. He has nothing but time.",
  playerDeck: playerStarterDeck("wrath"),
  boss: {
    name: "Skullcrusher Vex",
    sin: "wrath",
    epithet: "He Who Drinks the Wound",
    deck: bossDeck("wrath", "boss_wrath_2_bloodroar"),
    hpBoost: 80,
  },
  unlockedBy: "wrath_1",
};

const WRATH_ACT_3: CampaignMission = {
  id: "wrath_3",
  sin: "wrath",
  act: 3,
  title: "The Apostate",
  hook: "Erebus burned a cathedral down. Then he kept going.",
  intro:
    "Erebus used to be a cleric. Then he had a theological disagreement with everyone. " +
    "He preaches now, between strikes. About how Wrath is the only honest prayer. About how the rest of you are tourists. " +
    "His Final Hour is real. He's saving it for you. Don't let him reach it cheap.",
  outro:
    "Erebus kneels — the closest thing to reverence he's offered anyone since the cathedral fell. " +
    "He won't say you've earned Wrath. He'll just stop trying to take it from you.",
  defeatLine: "Erebus smiles, almost gentle. The Apostate has time. So do you, technically.",
  playerDeck: playerStarterDeck("wrath"),
  boss: {
    name: "Erebus",
    sin: "wrath",
    epithet: "The Apostate",
    deck: bossDeck("wrath", "boss_wrath_3_finalhour"),
    hpBoost: 160,
  },
  unlockedBy: "wrath_2",
};

// ─── Sloth: The Cell / The Drowsing / The Eternal ────────────────

const SLOTH_ACT_1: CampaignMission = {
  id: "sloth_1",
  sin: "sloth",
  act: 1,
  title: "The Cell",
  hook: "An anchorite who hasn't moved in a decade. Reaching them is the fight.",
  intro:
    "They lock the doors before you arrive. Then they lock them again behind you. " +
    "The Anchorite Aldon doesn't have to fight you — he just has to wait. " +
    "He's been waiting longer than you've been alive. Hit him often, hit him fast. " +
    "If he settles in, you don't make it out.",
  outro:
    "Aldon doesn't react when you finish him. He just blinks, slowly. " +
    "You can't tell if he's seen you. The chains slacken, a little. The door stays where it is.",
  defeatLine: "Aldon doesn't smile. He resettles. He has time.",
  playerDeck: playerStarterDeck("sloth"),
  boss: {
    name: "The Anchorite Aldon",
    sin: "sloth",
    epithet: "Bound to the Cell",
    deck: bossDeck("sloth", "boss_sloth_1_ironpatience"),
    hpBoost: 0,
  },
  unlockedBy: null,
};

const SLOTH_ACT_2: CampaignMission = {
  id: "sloth_2",
  sin: "sloth",
  act: 2,
  title: "The Drowsing",
  hook: "A garden where every plant breathes you in.",
  intro:
    "Mother Slumber doesn't have a face, exactly. She has a posture. " +
    "She is sitting in the centre of a garden that drinks people quietly, and she will be very gracious about you joining the soil. " +
    "The flowers don't care who wins. They care who loses slower. " +
    "Don't slow down.",
  outro:
    "Mother Slumber bows once, the way trees bow before a storm. " +
    "The garden goes back to breathing without you in it. " +
    "You won't sleep tonight. You'll be too proud.",
  defeatLine: "You don't remember sitting down. You don't remember closing your eyes.",
  playerDeck: playerStarterDeck("sloth"),
  boss: {
    name: "Mother Slumber",
    sin: "sloth",
    epithet: "She Who Breathes the Room Out",
    deck: bossDeck("sloth", "boss_sloth_2_drowse"),
    hpBoost: 90,
  },
  unlockedBy: "sloth_1",
};

const SLOTH_ACT_3: CampaignMission = {
  id: "sloth_3",
  sin: "sloth",
  act: 3,
  title: "The Eternal",
  hook: "Something that has been here longer than the arena has.",
  intro:
    "They don't tell you what The Eternal is, because nobody knows. " +
    "The arena was built around it — the arena is, in some sense, an apology. " +
    "It does not strike. It accumulates. By round four it will own the board. By round six it will own you. " +
    "Don't let it reach round six.",
  outro:
    "The Eternal does not die so much as elsewhere. Something distant inside it stops, and somewhere else, something starts. " +
    "You leave before whatever-that-is finds you. Wrath was a tantrum. Sloth was a verdict.",
  defeatLine: "The Eternal keeps eating. It has all the time. You did not.",
  playerDeck: playerStarterDeck("sloth"),
  boss: {
    name: "Older Than the Bell",
    sin: "sloth",
    epithet: "The Eternal",
    deck: bossDeck("sloth", "boss_sloth_3_aeon"),
    hpBoost: 175,
  },
  unlockedBy: "sloth_2",
};

// ─── Greed: The Counting House / The Vault / The Plutarch ───────

const GREED_ACT_1: CampaignMission = {
  id: "greed_1",
  sin: "greed",
  act: 1,
  title: "The Counting House",
  hook: "A clerk with a quill that draws blood as ink.",
  intro:
    "The Counting House isn't a building. It's an idea — that everything has a price, and someone has been keeping the receipts. " +
    "Maeven doesn't speak unless she's asking for a number. " +
    "She's been collecting on debts you don't remember owing, and keeping ledger on this fight for longer than you think. " +
    "Don't let her finish the column.",
  outro:
    "Maeven hands you back what you didn't know she'd taken. She doesn't apologize — clerks never do. " +
    "She writes a small note in your margin. You'll think about it later.",
  defeatLine: "Maeven adds you to the column without ceremony. Just a small mark.",
  playerDeck: playerStarterDeck("greed"),
  boss: {
    name: "The Clerk Maeven",
    sin: "greed",
    epithet: "Keeper of the Column",
    deck: bossDeck("greed", "boss_greed_1_tithe"),
    hpBoost: 0,
  },
  unlockedBy: null,
};

const GREED_ACT_2: CampaignMission = {
  id: "greed_2",
  sin: "greed",
  act: 2,
  title: "The Vault",
  hook: "A door behind a door behind a price.",
  intro:
    "Octavia keeps the Vault. The Vault keeps her. Nobody is sure which came first. " +
    "The trick with Octavia is that she's been billing you for every step you've taken since you walked in. " +
    "By the time you're standing in front of her, you owe more than you came in with. " +
    "Pay the debt with damage. Or don't pay it at all.",
  outro:
    "Octavia opens a door behind her, just for a moment. You see something glinting in there. " +
    "She closes it before you can ask. She nods, once. The Vault accepts you, conditionally.",
  defeatLine: "Octavia tabulates your loss without surprise. The Vault was never going to be opened by you.",
  playerDeck: playerStarterDeck("greed"),
  boss: {
    name: "Vault-Keeper Octavia",
    sin: "greed",
    epithet: "Door Behind the Door",
    deck: bossDeck("greed", "boss_greed_2_ledger_strike"),
    hpBoost: 90,
  },
  unlockedBy: "greed_1",
};

const GREED_ACT_3: CampaignMission = {
  id: "greed_3",
  sin: "greed",
  act: 3,
  title: "The Plutarch",
  hook: "Owns most things, including the rules of this fight.",
  intro:
    "Cassivus does not enter. He arrives, the way weather arrives. " +
    "He owns the Counting House. He owns the Vault. He owns, technically, the room you are standing in, the air you're breathing, and several minor parts of your liver. " +
    "He doesn't fight people. He liquidates them. " +
    "Make the liquidation expensive.",
  outro:
    "Cassivus does the closest thing to surprise his face has done in fifty years. " +
    "He hands you a piece of paper. You realize it's a deed. To something. " +
    "He doesn't say what. He'll tell you the next time you meet — if there is one.",
  defeatLine: "Cassivus does not gloat. Cassivus does paperwork. Several documents related to your defeat have already been filed.",
  playerDeck: playerStarterDeck("greed"),
  boss: {
    name: "Cassivus",
    sin: "greed",
    epithet: "The Plutarch",
    deck: bossDeck("greed", "boss_greed_3_liquidation"),
    hpBoost: 175,
  },
  unlockedBy: "greed_2",
};

// ─── Envy: The Mirror / The Twin / The Hollow ────────────────────

const ENVY_ACT_1: CampaignMission = {
  id: "envy_1",
  sin: "envy",
  act: 1,
  title: "The Mirror",
  hook: "Someone wearing your face. Smiling like they earned it.",
  intro:
    "You walk in. You're already in the room. " +
    "Your reflection — but wrong, because it's looking at you and you aren't looking at it. " +
    "The Mirror has been practicing your moves. It's been practicing your face. It probably knows how you breathe by now. " +
    "Beat the version of you that doesn't have to live with you.",
  outro:
    "The Mirror cracks, decorously. The face inside it slides off. " +
    "Whatever was behind goes back to whatever it was before you arrived. " +
    "You feel slightly less like an original.",
  defeatLine: "The Mirror smiles your smile, but better. It's been watching.",
  playerDeck: playerStarterDeck("envy"),
  boss: {
    name: "The Mirror",
    sin: "envy",
    epithet: "Wearing Your Face",
    deck: bossDeck("envy", "boss_envy_1_glasswork"),
    hpBoost: 0,
  },
  unlockedBy: null,
};

const ENVY_ACT_2: CampaignMission = {
  id: "envy_2",
  sin: "envy",
  act: 2,
  title: "The Twin",
  hook: "Whatever you build, they build better, smaller, faster.",
  intro:
    "There's a story about a twin who was born late. They grew up watching the older twin — what they ate, who they kissed, what they were good at. " +
    "The older twin never noticed. The older twin is now in front of you. " +
    "You are not the older twin in this story. " +
    "Build first. Build fast. Don't show your hand.",
  outro:
    "The Twin doesn't look defeated. They look thoughtful. " +
    "They've taken notes. You'll see them again, with whatever they learned today.",
  defeatLine: "The Twin doesn't celebrate. They've already moved on to the next thing they want.",
  playerDeck: playerStarterDeck("envy"),
  boss: {
    name: "The Twin",
    sin: "envy",
    epithet: "Born Late, Catching Up",
    deck: bossDeck("envy", "boss_envy_2_replica"),
    hpBoost: 90,
  },
  unlockedBy: "envy_1",
};

const ENVY_ACT_3: CampaignMission = {
  id: "envy_3",
  sin: "envy",
  act: 3,
  title: "The Hollow",
  hook: "An empty crown looking for a head.",
  intro:
    "The Hollow is what envy becomes when it eats everything in its line of sight, including itself. " +
    "There's a crown. There's nothing under it. The crown wants a head — has been wanting a head for a very long time. " +
    "The trick is not to want the crown. " +
    "The trick is to be more annoying than the crown is patient.",
  outro:
    "The Hollow inhales for the first time in a century. You feel it pull at your edges. " +
    "Then it stops. The crown clatters. " +
    "It has chosen, slowly, to want nothing for a moment. Lucky you.",
  defeatLine: "The Hollow finds something to want, briefly. You. Then loses interest, because there is so little to take.",
  playerDeck: playerStarterDeck("envy"),
  boss: {
    name: "The Hollow",
    sin: "envy",
    epithet: "An Empty Crown",
    deck: bossDeck("envy", "boss_envy_3_inheritance"),
    hpBoost: 175,
  },
  unlockedBy: "envy_2",
};

// ─── Pride: The Throne / The Idol / The Apex ─────────────────────

const PRIDE_ACT_1: CampaignMission = {
  id: "pride_1",
  sin: "pride",
  act: 1,
  title: "The Throne",
  hook: "A boy-king with one good speech and zero humility.",
  intro:
    "The Boy-King Velys is fifteen, has a kingdom to inherit, and absolutely nothing to lose. " +
    "He's been told he's special since the day he was born. He has, frankly, evidence. " +
    "He'll ask if you've heard of him. " +
    "Don't answer. Hit him before the speech lands.",
  outro:
    "Velys looks at you, genuinely surprised, and laughs. He likes you. He'll remember this. " +
    "That might be a problem later. For today, you're alive and he's impressed.",
  defeatLine: "Velys doesn't even look down at you. He's already onto the next sentence.",
  playerDeck: playerStarterDeck("pride"),
  boss: {
    name: "Boy-King Velys",
    sin: "pride",
    epithet: "One Good Speech",
    deck: bossDeck("pride", "boss_pride_1_coronation"),
    hpBoost: 0,
  },
  unlockedBy: null,
};

const PRIDE_ACT_2: CampaignMission = {
  id: "pride_2",
  sin: "pride",
  act: 2,
  title: "The Idol",
  hook: "Built of statues, all of itself.",
  intro:
    "The Idol of Selene is, technically, a religion. There are temples. There is iconography. " +
    "In front of you is a statue that has decided it's done waiting for worshippers. " +
    "It walks slow, hits enormous, and considers itself a building rather than an opponent. " +
    "Don't pray. Don't kneel. Hit the statue until it remembers it was carved by hands.",
  outro:
    "The Idol cracks at the base. It's been waiting to crack for a long time. " +
    "Whatever it represented goes back to representing nothing. " +
    "The temples will call it heresy. They aren't wrong.",
  defeatLine: "The Idol does not move to acknowledge you. It is already what it was.",
  playerDeck: playerStarterDeck("pride"),
  boss: {
    name: "The Idol of Selene",
    sin: "pride",
    epithet: "Carved By Hands It Forgot",
    deck: bossDeck("pride", "boss_pride_2_apotheosis"),
    hpBoost: 90,
  },
  unlockedBy: "pride_1",
};

const PRIDE_ACT_3: CampaignMission = {
  id: "pride_3",
  sin: "pride",
  act: 3,
  title: "The Apex",
  hook: "It refuses to acknowledge defeat. The fight ends when you do.",
  intro:
    "Apex has not lost. Apex has decided this is a structural property of reality, not a fact about Apex's skill. " +
    "Apex will continue to not lose by simply not stopping. " +
    "By round six, Apex will be, in some real sense, the room. By round seven, you will be furniture. " +
    "Make this hurt before then.",
  outro:
    "Apex stops. Not falls — stops. There is no precedent for it. " +
    "Apex looks at you the way you would look at someone who broke physics. " +
    "Then Apex inclines its head, very slightly, and walks out. " +
    "Pride is not what you take. It's what you decline to keep.",
  defeatLine: "Apex did not lose. The fight simply ended in the only way it could.",
  playerDeck: playerStarterDeck("pride"),
  boss: {
    name: "Apex",
    sin: "pride",
    epithet: "Has Never",
    deck: bossDeck("pride", "boss_pride_3_unbroken"),
    hpBoost: 175,
  },
  unlockedBy: "pride_2",
};

// ─── Full mission list ───────────────────────────────────────────

export const CAMPAIGN_MISSIONS: CampaignMission[] = [
  WRATH_ACT_1,
  WRATH_ACT_2,
  WRATH_ACT_3,

  SLOTH_ACT_1,
  SLOTH_ACT_2,
  SLOTH_ACT_3,

  GREED_ACT_1,
  GREED_ACT_2,
  GREED_ACT_3,

  ENVY_ACT_1,
  ENVY_ACT_2,
  ENVY_ACT_3,

  PRIDE_ACT_1,
  PRIDE_ACT_2,
  PRIDE_ACT_3,

  stub("lust_1", "lust", 1, "The Salon", "Charm with a knife in it."),
  stub("lust_2", "lust", 2, "The Snare", "Beautiful. Patient. Hungry."),
  stub("lust_3", "lust", 3, "The Devourer", "What lust looks like when it stops pretending."),

  stub("gluttony_1", "gluttony", 1, "The Feast", "An endless banquet. The plates are people."),
  stub("gluttony_2", "gluttony", 2, "The Banquet", "A host who measures guests in courses."),
  stub("gluttony_3", "gluttony", 3, "The Maw", "It just keeps eating. There is no after."),
];

const MISSIONS_BY_ID: Record<string, CampaignMission> = Object.fromEntries(
  CAMPAIGN_MISSIONS.map((m) => [m.id, m])
);

export function getMissionById(id: string): CampaignMission | undefined {
  return MISSIONS_BY_ID[id];
}

export function getMissionsForSin(sin: SinType): CampaignMission[] {
  return CAMPAIGN_MISSIONS.filter((m) => m.sin === sin).sort((a, b) => a.act - b.act);
}

/** Player has completed a mission if its id is in the completed set. */
export function isMissionUnlocked(
  mission: CampaignMission,
  completedIds: ReadonlySet<string>
): boolean {
  if (mission.comingSoon) return false;
  if (mission.unlockedBy === null) return true;
  return completedIds.has(mission.unlockedBy);
}

/** Twist card IDs referenced by missions, for test integrity checks. */
export const ALL_TWIST_CARD_IDS = new Set(BOSS_CARDS.map((c) => c.id));
